name: Ejecutar Script Diario

on:
  schedule:
    - cron: '0 21 * * *'  # Esto ejecutará el script a las 18 hs hora de Buenos Aires (21:00 UTC)
  workflow_dispatch:  # Esto te permite ejecutar el workflow manualmente desde GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar el script
      run: python capturpre.py
